# Generated by Django 2.0 on 2017-12-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash payment method'), ('card', 'Card payment method')], max_length=4),
        ),
    ]
