INSERT INTO products (category, name, price) VALUES ('vegetables', 'apple', 24.7);
INSERT INTO products (category, name, price) VALUES ('vegetables', 'pineapple', 86.4);
INSERT INTO products (category, name, price) VALUES ('vegetables', 'avocado', 19.2);
INSERT INTO products (category, name, price) VALUES ('vegetables', 'mango', 40.1);
INSERT INTO products (category, name, price) VALUES ('vegetables', 'cherry', 92.9);
INSERT INTO products (category, name, price) VALUES ('vegetables', 'feijoa', 32.2);
INSERT INTO products (category, name, price) VALUES ('vegetables', 'lemon', 12.6);
INSERT INTO products (category, name, price) VALUES ('vegetables', 'lime', 60.1);
INSERT INTO products (category, name, price) VALUES ('vegetables', 'peach', 58.5);
INSERT INTO products (category, name, price) VALUES ('condiments', 'mustard', 46.8);
INSERT INTO products (category, name, price) VALUES ('condiments', 'ketchup', 87.5);
INSERT INTO products (category, name, price) VALUES ('condiments', 'salt', 42.5);
INSERT INTO products (category, name, price) VALUES ('condiments', 'sugar', 20.8);
INSERT INTO products (category, name, price) VALUES ('condiments', 'chili', 16.6);
INSERT INTO products (category, name, price) VALUES ('condiments', 'cream cheese', 37.7);
INSERT INTO products (category, name, price) VALUES ('condiments', 'barbecue sauce', 27.1);
INSERT INTO products (category, name, price) VALUES ('condiments', 'garlic sauce', 77.3);
INSERT INTO products (category, name, price) VALUES ('fruits', 'cabbage', 72.9);
INSERT INTO products (category, name, price) VALUES ('fruits', 'carrot', 68.3);
INSERT INTO products (category, name, price) VALUES ('fruits', 'potato', 99.8);
INSERT INTO products (category, name, price) VALUES ('fruits', 'celery', 79.1);
INSERT INTO products (category, name, price) VALUES ('fruits', 'pumpkin', 81.1);
INSERT INTO products (category, name, price) VALUES ('fruits', 'kale', 31.3);
INSERT INTO products (category, name, price) VALUES ('fruits', 'lettuce', 24.9);
INSERT INTO products (category, name, price) VALUES ('fruits', 'artichoke', 91.0);
INSERT INTO products (category, name, price) VALUES ('fruits', 'broccoli', 69.7);
